<?php

namespace migration_classes\release_1;
use Doctrine_Migration_Base;

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration_004 extends Doctrine_Migration_Base
{
  public function migrate($direction)
  {
    $direction = $direction == 'up' ? 'down' : 'up';
    $this->table($direction, 'migration_profile', array('id' => array('type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true), 'name' => array('type' => 'string', 'length' => 255)), array('indexes' => array(), 'primary' => array(0 => 'id')));
  }
}
